---
title: "example 1"
author: "Bryan Pang"
date: "2022-12-01"
output: html_document
---

The sdksfsdfks

# This is a header

```{r load-data, message=FALSE}
library(tidyverse)
library(kableExtra)
library(rmarkdown)
library(ggpubr) #used for ggarrange function 

#This is a comment
#Load the dataset
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from ?european countries in 2007 showing the countries
#wish the largest life expectancy on top
euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>%
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp))%>%
                    rename("Country" = country, "Population Size" = pop,
                           "Life Expectancy" = lifeExp, "GDP" = gdpPercap)

```

here we have our data set...

```{r create-table}
#in tideverse, %>% means using the output of the former argument as the input of the next
euro_data_tbl %>%
  kbl() %>%
  kable_styling(bootstrap_options = "striped", full_width = F) %>% 
  scroll_box(width = "100%", height = "200px")
```
Here is an example of how to display a massive table 

```{r paged-table}
paged_table(euro_data_tbl)
```

create new data set to include only data from Europe:

```{r fig-data}
#keep on European data and change year to factor
euro_data_fig <- pop_data %>% 
                    filter(continent == "Europe")  %>% 
                    mutate(year=as_factor(year))

#keep only United Kingdom data and change year to factor
uk_data_fig <- pop_data %>%
                    filter(country == "United Kingdom") %>%
                    mutate(year=as_factor(year))

```

The life expectancy for Europe over the years is plotted as following:

```{r fig, warning=FALSE, fig.cap="Life Expectancy in Europe over the years"}
#Euro plot
euro_plot <- euro_data_fig %>%
                ggplot(mapping=aes(x=year, y=lifeExp)) +
                geom_violin() +
                stat_summary(fun.y = median, geom = "point")

#draw euro plot
euro_plot

```

Comparison of life expectancy from Europe and United Kingdom:

```{r fig-comp, warning=FALSE, fig.cap="Life Expectancy in European and UK over the years"}
#UK plot
uk_plot <- uk_data_fig %>%
                ggplot(mapping=aes(x=year, y=lifeExp)) +
                geom_point()

#draw euro plot next to UK plot
ggarrange(euro_plot, uk_plot, ncol=2, nrow=1, labels="AUTO")
```

